[package]
name = "mnemonic_word_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rust-crypto = "0.2.36"
itertools = "0.10.3"
ring = "0.16.20"